apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: metallb-advertisment
spec:
  ipAddressPools:
  {{- range .Values.local.pools -}}
  {{- if .bgpAdvertise }}
    - {{ .name }}-pool
  {{- end -}}
  {{ end }}
---
