cert-manager:
  # If CRDs are installed alongside this chart, Helm doesn't
  # apply them before other resources, leading to a `resource
  # mapping not found`; therefore CRDs have to be installed
  # manually. As a result, they are disabled here.
  installCRDs: true

acme:
  email: letsencrypt@totaldebug.uk
